version: "3.8"
services:

  mysql:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - ../../../mysql-dump:/docker-entrypoint-initdb.d/dump_netflix3.sql
      - ../../../data-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: database
      MYSQL_DATABASE: Netflix
      MYSQL_HOST: localhost 

  flask_app:
    depends_on:
      - mysql
    restart: on-failure #if build fails, restart again (just to wait for db to be ready for connections)
    image: python-flask #where is this used? i said PyMySQL-python-flask and got error docker daemon not running. araiwa/
    build: .
    ports:
      - "5000:5000"
      - "8888:8888"
    volumes:
      - .:/code
    environment:
      TJ_MYSQL_PASSWORD: database
      TJ_MYSQL_HOST: mysql                    
      TJ_MYSQL_DATABASE: Netflix
      TJ_MYSQL_PORT: 3306
      TJ_APPLICATION_PORT: 5000
      TJ_APPLICATION_HOST: 0.0.0.0

volumes: 
  data-test:
  mysql-dump:
